server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
  port: 9091
  servlet:
    session:
      cookie:
        name: BUSINESS_SERVER_SESSION

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qyxt_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  profiles:
    active: dev
  freemarker:
    suffix: .ftl
    prefix: /
    settings:
      tag_syntax: auto_detect
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  resources:
    static-locations: ["file:./static/","file:./business-server/static/"]
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: -1
        max-idle: 8
  cache:
    type: redis
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    locale: zh
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapper-locations: classpath*:cn/xluobo/business/**/**/repo/mapping/**.xml
  # 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性，具体使用请结合 枚举注入 查看。
  # type-enums-package:
  check-config-location: true # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  # 通过该属性可指定 MyBatis 的执行器，MyBatis 的执行器总共有三种：
  executor-type: simple
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: true #当设置为 true 的时候，懒加载的对象可能被任何懒属性全部加载，否则，每个属性都按需加载。需要和 lazyLoadingEnabled 一起使用。
  global-config:
    db-config:
      # 是否开启大写命名，默认不开启
      capital-mode: false
      logic-delete-field: delete_flag
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id
logging:
  config: classpath:logback-spring.xml

wx:
  miniapp:
    configs:
      - appid: appid
        secret: secret
        token: token
        aesKey: aesKey
        msgDataFormat: JSON
