server:
  port: 9091
  servlet:
    session:
      cookie:
        #本地调oauth2 授权时 会出现 Possible CSRF detected - state parameter was required but no state could be found，解决方案 详见 #https://www.cnblogs.com/xuzimian/p/11133545.html
        #避免本地调测 localhost 不同端口 导致 Session的标识id被覆盖
        name: BUSINESS_SERVER_SESSION


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9092/resource/userInfo/me
      token-info-uri: http://localhost:9092/oauth/check_token
      id: business-server
      jwt:
        key-uri: http://localhost:9092/oauth/token_key
        # 如果没有配置这项，会自动联网获取
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsFMjMVbVqG/htwps7DxQ
          c1Y+33FRC38cUEqwi7PlQIT2G/ARK0WDKRnOeTMpRMuRwTwy7Kgy4M8HhvNJCo2G
          ZO5U71uaL6q0QG4wiRdJrfg/ZtPuQNP4yj/t8UVOMpHcnTE0gOqy+b6ukFCENaPp
          xRs7rOiX2eVJRMUxaQlb1OF0JBRjlHmzJx7gY45UHa046gUmzL4igSXYAWSv3DVc
          RIUksIt0adn7lRn/gIzm3OKGn92DHj22xJs6iiRFD2WgWJxazhNMYt8HSljcsF9v
          v78janOBC8KQSAe9fkijEH3Uhde/GfWQsGP1JCGMy1zg5lTn+DmBtGWWsjaLBFti
          1QIDAQAB
          -----END PUBLIC KEY-----
    client:
      access-token-uri: http://localhost:9092/oauth/token
      user-authorization-uri: http://localhost:9092/oauth/authorize
      client-id: business-server
      client-secret: 123456
      grant-type: authorization_code
      scope: all
      auto-approve-scopes: all

      # 授权回调地址
      redirect-uri: http://localhost:9091/oauth2/callback
    sso:
      # sso token统一url
      sso-redirect-url: http://localhost:9092/ssoLoginRedirect?s=%s&t=%s

# 小程序oath client
wechat:
  oauth2:
    client:
      client-id: wechatminiapp
      client-secret: 123456

wx:
  miniapp:
    configs:
      - appid: 1
        secret: 2
        token: 3
        aesKey: gZZI8aq2UztVXUSyIo18Xup4uPiCYKlRCBa9hZCYi5L
        msgDataFormat: JSON

xluobo:
  tool:
    gen:
      config:
        base-package: com.study.business
        template-configs:
          - templateFileName: "controller.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.controller"
            outFileName: "{className}Controller.java"
            javaType: CONTROLLER
            outPath: "/business-server/src/main/java/"
          - templateFileName: "entity.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.repo.model"
            outFileName: "{className}.java"
            javaType: ENTITY
            outPath: "/base-service/src/main/java/"
          - templateFileName: "mapper.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.repo.mapper"
            outFileName: "{className}Mapper.java"
            javaType: MAPPER
            outPath: "/base-service/src/main/java/"
          - templateFileName: "mapper.xml.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.repo.mapping"
            outFileName: "{className}Mapper.xml"
            outPath: "/base-service/src/main/java/"
          - templateFileName: "iService.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.service"
            outFileName: "I{className}Service.java"
            javaType: ISERVICE
            outPath: "/base-service/src/main/java/"
          - templateFileName: "serviceImpl.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.service.impl"
            outFileName: "{className}ServiceImpl.java"
            javaType: SERVICEIMPL
            outPath: "/base-service/src/main/java/"
          - templateFileName: "reqSearchEntity.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.domain.req"
            outFileName: "ReqSearch{className}.java"
            javaType: REQ_ENTITY
            outPath: "/base-service/src/main/java/"
          - templateFileName: "index.vue.ftl"
            packageOrDir: "views.{moduleName}.{childModuleName}.{businessName}"
            outFileName: "index.vue"
            prefixPkg: false
            outPath: "/web-admin/src/"
          - templateFileName: "api.js.ftl"
            packageOrDir: "api.{moduleName}.{childModuleName}.{businessName}"
            outFileName: "index.js"
            prefixPkg: false
            outPath: "/web-admin/src/"
          - templateFileName: "businessService.java.ftl"
            packageOrDir: ".{moduleName}.{childModuleName}.service"
            outFileName: "Business{className}Service.java"
            javaType: BUSINESS_SERVICE
            outPath: "/business-server/src/main/java/"
          - templateFileName: "menu.sql.ftl"
            packageOrDir: "sql"
            outFileName: "{className}Menu.sql"
            prefixPkg: false
            outPath: "/business-server/src/main/resources/"
  upload:
    file-path: /Users/zhangxiansheng/IdeaProject/gitee/qyxt/upload
    temp-save-export-path: /Users/zhangxiansheng/IdeaProject/gitee/qyxt/export
    temp-save-import-path: /Users/zhangxiansheng/IdeaProject/gitee/qyxt/import

